Repository NOW-SOPT-CDSP-TEAM-WEB4/Notefolio-Client, pull requests merged in 2024-05, with the labels that each got.

#2 [Init] 폴더구조 + 라우팅 설정
  package.json
  public/.gitkeep
  public/vite.svg
  src/App.css
  src/App.tsx
  src/Router.tsx
  src/assets/img/.gitkeep
  src/assets/index.ts
  src/assets/react.svg
  src/assets/svg/.gitkeep
  src/components/Page1/.gitkeep
  src/components/Page2/.gitkeep
  src/components/Page3/.gitkeep
  src/components/Page4/.gitkeep
  src/components/common/.gitkeep
  src/hooks/Page1/.gitkeep
  src/hooks/Page2/.gitkeep
  src/hooks/Page3/.gitkeep
  src/hooks/Page4/.gitkeep
  src/hooks/common/.gitkeep
  src/index.css
  src/libs/.gitkeep
  src/main.tsx
  src/pages/.gitkeep
  src/styles/.gitkeep
  src/utils/Page1/.gitkeep
  src/utils/Page2/.gitkeep
  src/utils/Page3/.gitkeep
  src/utils/Page4/.gitkeep
  src/utils/common/.gitkeep
  yarn.lock
Labels: ⚙️ init

#7 [ Init ] svg 세팅
  package.json
  svg.d.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: ⚙️ init

#9 [ Init ] eslint + prettier 설정
  .eslintignore
  .eslintrc.cjs
  .eslintrc.json
  .prettierignore
  .prettierrc
  package.json
  src/App.tsx
  src/main.tsx
  svg.d.ts
  vite.config.ts
  yarn.lock
Labels: ⚙️ init

#21 [ Common ] Chips 리스트 컴포넌트 구현
  .eslintrc.json
  src/assets/index.ts
  src/assets/svg/.gitkeep
  src/assets/svg/ic_check_white.svg
  src/assets/svg/ic_next_button.svg
  src/components/common/.gitkeep
  src/components/common/ChipList/Chip.tsx
  src/components/common/ChipList/ChipsList.tsx
  src/components/common/ChipList/constantEx.ts
  src/components/common/ChipList/types/chipsListType.ts
Labels: 🏠 common

#23 [ Init ] 미적용 세부 세팅
  src/Router.tsx
  src/components/Community/.gitkeep
  src/components/Home/.gitkeep
  src/components/Recruit/.gitkeep
  src/components/Search/.gitkeep
  src/components/common/ChipList/Chip.tsx
  src/hooks/Community/.gitkeep
  src/hooks/Home/.gitkeep
  src/hooks/Recruit/.gitkeep
  src/hooks/Search/.gitkeep
  src/pages/.gitkeep
  src/pages/Community/Community.tsx
  src/pages/Home/Home.tsx
  src/pages/Recruit/Recruit.tsx
  src/pages/Search/Search.tsx
  src/styles/theme.ts
  src/utils/Community/.gitkeep
  src/utils/Home/.gitkeep
  src/utils/Recruit/.gitkeep
  src/utils/Search/.gitkeep
Labels: ⚙️ init

#24 [ Common ] Header 컴포넌트 구현
  src/assets/index.ts
  src/assets/svg/ic_logo_sim.svg
  src/assets/svg/ic_loud.svg
  src/assets/svg/ic_sym.svg
  src/assets/svg/ic_top_bar.svg
  src/components/common/Header/Header.tsx
Labels: 🏠 common

#25 [ Common ] TopNav 구현
  src/assets/index.ts
  src/assets/svg/icons_New.svg
  src/assets/svg/icons_Search.svg
  src/assets/svg/logo.svg
  src/components/common/topNav/TopNav.tsx
  src/styles/theme.ts
Labels: 🏠 common

#27 [ Init ] 페이지 Outlet 세팅
  src/Roots.tsx
  src/Router.tsx
  src/components/common/TopNav/TopNav.tsx
Labels: ⚙️ init

#31 [ Recruit ] 채용 페이지 상단 Banner 컨테이너 구현
  src/assets/img/.gitkeep
  src/assets/img/img_recruit_banner.svg
  src/assets/index.ts
  src/components/Recruit/.gitkeep
  src/components/Recruit/BannerContainer/BannerContainer.tsx
  src/pages/Recruit/Recruit.tsx
  src/styles/theme.ts
Labels: ✨feat

#35 [ Recruit ] 적극적으로 채용 중인 회사 Section 구현
  src/assets/img/img_active_recruit_1.png
  src/assets/img/img_active_recruit_2.png
  src/assets/img/img_active_recruit_3.png
  src/assets/index.ts
  src/assets/svg/ic_clock.svg
  src/assets/svg/ic_logo_daily_morning.svg
  src/assets/svg/ic_logo_studio_edink.svg
  src/assets/svg/ic_logo_stunning.svg
  src/components/Recruit/ActiveRecruitItem/ActiveRecruitItem.tsx
  src/components/Recruit/ActiveRecruitSection/ActiveRecruitSection.tsx
  src/constants/Recruit/recruitConstants.tsx
  src/pages/Recruit/Recruit.tsx
  src/types/Recruit/recruitTypes.ts
Labels: ✨feat

#39 [ Search ] 검색 결과 페이지 퍼블리싱
  src/assets/img/.gitkeep
  src/assets/img/img_search_result_1.png
  src/assets/index.ts
  src/assets/svg/ic_arrow_down.svg
  src/assets/svg/ic_filter.svg
  src/assets/svg/ic_heart.svg
  src/assets/svg/ic_heart_filled.svg
  src/assets/svg/ic_heart_outlined.svg
  src/assets/svg/ic_logo_author_1.svg
  src/assets/svg/ic_view.svg
  src/components/Search/.gitkeep
  src/components/Search/SearchInputSection.tsx
  src/components/Search/SearchResultItem.tsx
  src/components/Search/SearchResultSection.tsx
  src/components/common/TopNav/TopNav.tsx
  src/pages/Search/Search.tsx
  src/types/Search/searchTypes.ts
Labels: ✨feat

#41 [ Recruit ] 디자인 포지션 채용 공고 Section 구현
  src/assets/img/img_designer_recruit_1.png
  src/assets/img/img_designer_recruit_10.png
  src/assets/img/img_designer_recruit_11.png
  src/assets/img/img_designer_recruit_2.png
  src/assets/img/img_designer_recruit_3.png
  src/assets/img/img_designer_recruit_4.png
  src/assets/img/img_designer_recruit_5.png
  src/assets/img/img_designer_recruit_6.png
  src/assets/img/img_designer_recruit_7.png
  src/assets/img/img_designer_recruit_8.png
  src/assets/img/img_designer_recruit_9.png
  src/assets/index.ts
  src/assets/svg/ic_designer_recruit_1.svg
  src/assets/svg/ic_designer_recruit_10.svg
  src/assets/svg/ic_designer_recruit_11.svg
  src/assets/svg/ic_designer_recruit_2.svg
  src/assets/svg/ic_designer_recruit_3.svg
  src/assets/svg/ic_designer_recruit_4.svg
  src/assets/svg/ic_designer_recruit_5.svg
  src/assets/svg/ic_designer_recruit_6.svg
  src/assets/svg/ic_designer_recruit_7.svg
  src/assets/svg/ic_designer_recruit_8.svg
  src/assets/svg/ic_designer_recruit_9.svg
  src/components/Recruit/ActiveRecruitItem.tsx
  src/components/Recruit/ActiveRecruitSection.tsx
  src/components/Recruit/BannerSection.tsx
  src/components/Recruit/DesignerRecruitItem.tsx
  src/components/Recruit/DesignerRecruitSection.tsx
  src/constants/Recruit/recruitConstants.tsx
  src/pages/Recruit/Recruit.tsx
  src/types/Recruit/recruitTypes.ts
Labels: ✨feat

#43 [ Init ] API 모듈 세팅
  .gitignore
  package.json
  src/libs/.gitkeep
  src/libs/api.ts
  yarn.lock
Labels: ⚙️ init

#46 [ Home ] 홈화면 국내 최고의 포트폴리오를 발견해보세요 section 구현 + 홈화면 캐러셀 구현
  src/assets/img/img_bestfolio_home_1.png
  src/assets/img/img_bestfolio_home_2.png
  src/assets/img/img_bestfolio_home_3.png
  src/assets/img/img_bestfolio_home_4.png
  src/assets/img/img_bestfolio_home_5.png
  src/assets/img/img_carousel_1.png
  src/assets/img/img_carousel_2.png
  src/assets/img/img_carousel_3.png
  src/assets/img/img_carousel_4.png
  src/assets/index.ts
  src/assets/svg/ic_check_left.svg
  src/assets/svg/ic_check_right.svg
  src/assets/svg/ic_cs_four.svg
  src/assets/svg/ic_cs_one.svg
  src/assets/svg/ic_cs_three.svg
  src/assets/svg/ic_cs_two.svg
  src/assets/svg/ic_empty_heart.svg
  src/assets/svg/ic_floggy.svg
  src/assets/svg/ic_frame.svg
  src/assets/svg/ic_grey_heart.svg
  src/assets/svg/ic_heart.svg
  src/assets/svg/ic_kinder.svg
  src/assets/svg/ic_mog.svg
  src/assets/svg/ic_molly.svg
  src/assets/svg/ic_studio.svg
  src/assets/svg/ic_view.svg
  src/components/Home/BestFolioItem/BestFolioItem.tsx
  src/components/Home/BsetFolioSection/BestFolioSection.tsx
  src/components/Home/CarouselContainer.tsx
  src/components/common/ChipList/HoemChipsTextList.ts
  src/components/common/ChipList/constantEx.ts
  src/constants/Home/homeConstants.tsx
  src/pages/Home/Home.tsx
  src/types/Home/homeTypes.tsx
Labels: ✨feat

#55 [ Community ] 새롭게 오픈한 프로그램/프로덕트 디자이너로 성장 섹션 구현
  src/assets/img/img_program_1.png
  src/assets/img/img_program_2.png
  src/assets/img/img_program_3.png
  src/assets/img/img_program_4.png
  src/components/Community/ProgramItem.tsx
  src/components/Community/ProgramSection.tsx
  src/pages/Community/Community.tsx
  src/types/Community/communityProps.ts
Labels: ✨feat

#60 [ Community ] 성장/커뮤니티 페이지 하단 인기 워크숍 섹션 구현
  src/assets/img/img_popular1.png
  src/assets/img/img_popular2.png
  src/assets/img/img_popular3.png
  src/assets/img/img_popular_bottom.png
  src/components/Community/PopularSection/PopularItem.tsx
  src/components/Community/PopularSection/PopularSection.tsx
  src/components/Community/ProgramSection/ProgramItem.tsx
  src/components/Community/ProgramSection/ProgramSection.tsx
  src/pages/Community/Community.tsx
  src/types/Community/communityProps.ts
Labels: ✨feat

#59 [ Home ] 노트폴리오 추천 section 구현
  src/assets/img/img_KUSH_1.png
  src/assets/img/img_KUSH_2.png
  src/assets/img/img_KUSH_3.png
  src/assets/img/img_Mozza_1.png
  src/assets/img/img_Mozza_2.png
  src/assets/img/img_Mozza_3.png
  src/assets/img/img_jaein_1.png
  src/assets/img/img_jaein_2.png
  src/assets/img/img_jaein_3.png
  src/assets/img/img_kio_1.png
  src/assets/img/img_kio_2.png
  src/assets/img/img_kio_3.png
  src/assets/img/img_pindit_1.png
  src/assets/img/img_pindit_2.png
  src/assets/img/img_pindit_3.png
  src/assets/index.ts
  src/assets/svg/ic_JAEIN.svg
  src/assets/svg/ic_KUSH.svg
  src/assets/svg/ic_Mozza.svg
  src/assets/svg/ic_pindit.svg
  src/assets/svg/ic_studioKIO.svg
  src/components/Home/DesignerRecruitItem/DesignerRecruitItem.tsx
  src/components/Home/NotefolioRecommendItem/NotefolioRecommendItem.tsx
  src/components/Home/NotefolioRecommendSection/NotefolioRecommendSection.tsx
  src/constants/Home/notefolioConstants.tsx
  src/pages/Home/Home.tsx
  src/types/Home/homeTypes.tsx
Labels: ✨feat

#63 [ Community ] 성장/커뮤니티 페이지 상단 캐러셀 구현
  src/assets/img/img_carousel_1.png
  src/assets/img/img_carousel_2.png
  src/assets/img/img_carousel_3.png
  src/assets/img/img_carousel_4.png
  src/assets/img/img_carousel_5.png
  src/assets/img/img_carousel_all_1.png
  src/assets/img/img_carousel_all_2.png
  src/assets/img/img_carousel_all_3.png
  src/assets/img/img_carousel_all_4.png
  src/assets/img/img_carousel_all_5.png
  src/assets/index.ts
  src/assets/svg/icons_arrowleft_rg.svg
  src/components/Community/GrowthSection/CommunityCarousel.tsx
  src/components/Community/GrowthSection/GrowthSection.tsx
  src/constants/Community/communityConstants.tsx
  src/types/Community/communityProps.ts
Labels: ✨feat

#61 [ Search ] 검색 GET API 연동
  src/assets/img/img_free1.svg
  src/assets/img/img_search_result_10.png
  src/assets/img/img_search_result_11.png
  src/assets/img/img_search_result_12.png
  src/assets/img/img_search_result_13.png
  src/assets/img/img_search_result_14.png
  src/assets/img/img_search_result_15.png
  src/assets/img/img_search_result_16.png
  src/assets/img/img_search_result_2.png
  src/assets/img/img_search_result_3.png
  src/assets/img/img_search_result_4.png
  src/assets/img/img_search_result_5.png
  src/assets/img/img_search_result_6.png
  src/assets/img/img_search_result_7.png
  src/assets/img/img_search_result_8.png
  src/assets/img/img_search_result_9.png
  src/assets/img/img_work_im1.svg
  src/assets/index.ts
  src/assets/svg/ic_logo_author_10.svg
  src/assets/svg/ic_logo_author_11.svg
  src/assets/svg/ic_logo_author_12.svg
  src/assets/svg/ic_logo_author_2.svg
  src/assets/svg/ic_logo_author_3.svg
  src/assets/svg/ic_logo_author_4.svg
  src/assets/svg/ic_logo_author_5.svg
  src/assets/svg/ic_logo_author_6.svg
  src/assets/svg/ic_logo_author_7.svg
  src/assets/svg/ic_logo_author_8.svg
  src/assets/svg/ic_logo_author_9.svg
  src/components/Search/SearchInputSection.tsx
  src/components/Search/SearchResultItem.tsx
  src/components/Search/SearchResultSection.tsx
  src/constants/Result/resultConstants.tsx
  src/hooks/Search/.gitkeep
  src/hooks/Search/useGetCreativeSearch.ts
  src/types/Search/searchTypes.ts
  src/utils/Search/.gitkeep
  src/utils/Search/getCreativeSearch.ts
Labels: 🚀api

#62 [ Common ] ChipsList 컴포넌트 scroll 이벤트에 throttle 적용하여 최적화
  src/components/common/ChipList/ChipsList.tsx
  src/utils/common/throttle.ts
Labels: ♻️refactor

#68 [ Home ] 크리에이티브 조회 GET API 연동
  package.json
  src/apis/Home/getCreativeInquire.ts
  src/assets/img/img_free1.svg
  src/assets/img/img_search_result_10.png
  src/assets/img/img_search_result_11.png
  src/assets/img/img_search_result_12.png
  src/assets/img/img_search_result_13.png
  src/assets/img/img_search_result_14.png
  src/assets/img/img_search_result_15.png
  src/assets/img/img_search_result_16.png
  src/assets/img/img_search_result_2.png
  src/assets/img/img_search_result_3.png
  src/assets/img/img_search_result_4.png
  src/assets/img/img_search_result_5.png
  src/assets/img/img_search_result_6.png
  src/assets/img/img_search_result_7.png
  src/assets/img/img_search_result_8.png
  src/assets/img/img_search_result_9.png
  src/assets/img/img_work_im1.svg
  src/assets/index.ts
  src/assets/svg/ic_logo_author_10.svg
  src/assets/svg/ic_logo_author_11.svg
  src/assets/svg/ic_logo_author_12.svg
  src/assets/svg/ic_logo_author_2.svg
  src/assets/svg/ic_logo_author_3.svg
  src/assets/svg/ic_logo_author_4.svg
  src/assets/svg/ic_logo_author_5.svg
  src/assets/svg/ic_logo_author_6.svg
  src/assets/svg/ic_logo_author_7.svg
  src/assets/svg/ic_logo_author_8.svg
  src/assets/svg/ic_logo_author_9.svg
  src/components/Home/BestFolioItem/BestFolioItem.tsx
  src/components/Home/BsetFolioSection/BestFolioSection.tsx
  src/components/common/ChipList/ChipsList.tsx
  src/constants/Home/homeConstants.tsx
  src/constants/Result/resultConstants.tsx
  src/hooks/Home/.gitkeep
  src/hooks/Search/.gitkeep
  src/hooks/Search/useGetCreativeSearch.ts
  src/types/Home/homeTypes.tsx
  src/types/Search/searchTypes.ts
  src/utils/Home/.gitkeep
  src/utils/Search/.gitkeep
  src/utils/Search/getCreativeSearch.ts
  src/utils/common/throttle.ts
  yarn.lock
Labels: 🚀api

#71 [ Community ] 프로그램 전체 조회 GET API 연동
  src/apis/Community/getProgram.tsx
  src/components/Community/ProgramSection/ProgramItem.tsx
  src/components/Community/ProgramSection/ProgramSection.tsx
  src/types/Community/communityProps.ts
Labels: 🚀api

#74 [ Community ] 워크샵 전체 조회 GET API 연동
  src/apis/Community/getWorkshop.tsx
  src/assets/img/img_popular_1.png
  src/assets/img/img_popular_2.png
  src/assets/img/img_popular_3.png
  src/components/Community/GrowthSection/CommunityArticleItem.tsx
  src/components/Community/GrowthSection/CommunityNavItem.tsx
  src/components/Community/PopularSection/PopularItem.tsx
  src/components/Community/PopularSection/PopularSection.tsx
  src/components/Community/ProgramSection/ProgramItem.tsx
  src/types/Community/communityProps.ts
Labels: 🚀api

#75 [ Home ] 크리에이티브 좋아요 POST/DELETE API 연동
  src/apis/Home/deleteCreativeLike.ts
  src/apis/Home/postCreativeLike.ts
  src/components/Home/BestFolioItem/BestFolioItem.tsx
  src/components/Home/BsetFolioSection/BestFolioSection.tsx
  src/constants/Home/homeConstants.tsx
  src/types/Home/homeTypes.tsx
Labels: 🚀api
